### PR TITLE
Using uTLS to support more blocking resistant client hellos

### PR DESCRIPTION
**Pull request by oxtoacart**
For getlantern/lantern-internal#2176

### CODE REVIEW

**Comment by joesis** [comment]
LGTM. The only concern is that `utls` may not be able to keep pace with `crypto/tls`, especially `utls` needs to work across Go versions while `crypto/tls` is shipped with Go. I expect the tests to catch critical errors, though.

**Comment by joesis** [comment]
I'd like to hear what @myleshorton say about it.

**Comment by oxtoacart** [comment]
I asked the author of uTLS if he keeps it up to date, this was his answer:

> Yes, I do keep it mostly up to date. Last upstream merge was about a month ago, the next one will probably be in half a year after tls 1.3 gets implemented, assuming there wouldn't be serious integration problems.

**Comment by joesis** [comment]
Then nothing to worry about. Merging!

**Comment by oxtoacart** [comment]
Thanks @joesis! My next step is integrating into flashlight.

**Pull request merged**
